---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
setwd("E:/wzy/wzy/bigchuangdata")
TS_covid_data<-read.csv("time_series_covid19_confirmed_US.csv")
TS_covid_data
```
```{r}
TS_covid_state<-aggregate(TS_covid_data[,12:ncol(TS_covid_data)], list(TS_covid_data$Province_State), sum)
```

```{r}
setwd("E:/wzy/wzy/bigchuangdata")
Trip_by_dis<-read.csv(file="Trips_by_Distance.csv")
Trip_by_dis<-na.omit(Trip_by_dis)
```

```{r}
Trip_by_dis
Trip_bystate<-aggregate(Trip_by_dis[,7:(ncol(Trip_by_dis)-1)],list(Trip_by_dis$State.Postal.Code,Trip_by_dis$Date),sum)
Trip_bystate
```

```{r}
Trip_goout_rate<-cbind(Trip_bystate$Group.1,Trip_bystate$Group.2,(Trip_bystate[,ncol(Trip_bystate)]+Trip_bystate[,ncol(Trip_bystate)-1])/(Trip_bystate[,3]+Trip_bystate[,4]),(Trip_bystate[,3]+Trip_bystate[,4]))
Trip_goout_rate<-data.frame(Trip_goout_rate)
Trip_goout_rate
```
```{r}
location_country<-TS_covid_data[,c(7,9,10)]
location_state<-aggregate(location_country[,c(2,3)],list(location_country[,1]),mean)
location_state
```
```{r}
setwd("E:/wzy/wzy/bigchuangdata")
states<-read.table("states1.txt",sep="\t")
states
```

```{r}
library(plyr)
colnames(states)<-c("X1","Group.1")
data<-join(states,location_state,by="Group.1")
data
```

```{r}
Fdist_between_states<-function(la1,la2,lo1,lo2){
  R<-6371
  ans<-2*R*asin(sqrt(sin((la1/180*pi-la2/180*pi)/2)^2+cos(la1/180*pi)*cos(la2/180*pi)*sin((lo1/180*pi-lo2/180*pi)/2)^2))
  return(ans)
}
```

```{r}
for(i in 1:50){
  data$disti<-matrix(0,nrow=50,ncol=1)
  for(j in 1:50){
    data$disti[j]<-Fdist_between_states(data$Lat[i],data$Lat[j],data$Long_[i],data$Long_[j])
  }
  temp=0
  for(j in 1:50){
    if(j!=i){
      temp=temp+1/data$disti[j]
    }
  }
  trip_goout_i<-Trip_goout_rate[which(Trip_goout_rate$X1==data$X1[i]),]
  states_out_i<-matrix(0,nrow=nrow(trip_goout_i),ncol=50)
  for(k in 1:50){
    if(k==i){
      next
    }
    for(j in 1:nrow(trip_goout_i)){
      states_out_i[j,k]=as.numeric(trip_goout_i[j,4])*as.numeric(trip_goout_i[j,3])/data$disti[k]/temp
    }
  }
  states_out_i<-data.frame(states_out_i)
  states_out_i$time<-trip_goout_i$X2
  assign(paste0("states_out",i),states_out_i)
}
```
```{r}
for(i in 1:50){
  states_in_i<-matrix(0,nrow=nrow(get(paste0("states_out",1))),ncol=50)
  for(j in 1:50){
    states_in_i[,j]=get(paste0("states_out",j))[,i]
  }
  states_in_i<-data.frame(states_in_i)
  states_in_i$time<-states_out_i$time
  assign(paste0("states_in",i),states_in_i)
}
```
```{r}
time<-unique(Trip_goout_rate$X2)
time<-time[which(time=="2020/01/22"):length(time)]
tail(time)
```

```{r}
TS_covid_state<-join(states,TS_covid_state,by="Group.1")
TS_covid_state
```

```{r}
i<-1
time<-time[which(time=="2020/04/01"):length(time)]
TS_covid_state_select<-TS_covid_state[,-(3:(which(colnames(TS_covid_state)=="X3.31.20")-1))]
TS_covid_state_select
TS_new_cases<-TS_covid_state_select[,1:2]
TS_new_cases
for(j in 3:(ncol(TS_covid_state_select)-1)){
  TS_new_cases[,j]<-TS_covid_state_select[,j+1]-TS_covid_state_select[,j]
}
colnames(TS_new_cases)[3:length(colnames(TS_new_cases))]<-time[1:(length(colnames(TS_new_cases))-2)]
TS_new_cases
```

```{r}
dezeros<-function(x){
  if(x<0){
    return(0)
  }
  else{
    return(x)
  }
}
TS_new_cases[,3:ncol(TS_new_cases)]<-dezeros(TS_new_cases[,3:ncol(TS_new_cases)])
TS_new_cases
```
```{r}
gamma<-1/3
TS_real_Infectious<-TS_new_cases
for(j in 3:(ncol(TS_new_cases)-1)){
  TS_real_Infectious[,j]<-1/gamma*TS_new_cases[,j+1]
}
TS_real_Infectious<-TS_real_Infectious[,-ncol(TS_real_Infectious)]
TS_real_Infectious
```
```{r}
for(i in 1:nrow(TS_real_Infectious)){
  for(j in 3:(ncol(TS_real_Infectious)-1)){
    if(TS_real_Infectious[i,j]==0){
      k=1
      while(TS_real_Infectious[i,j+k]==0){
        k=k+1
        if((j+k)>ncol(TS_real_Infectious)){
          break
        }
      }
      if((j+k)>ncol(TS_real_Infectious)){
          break
      }
      TS_real_Infectious[i,j]=floor(TS_real_Infectious[i,j+k]/(k+1))
      for(t in 1:(k-1)){
        TS_real_Infectious[i,j+t]=TS_real_Infectious[i,j]
      }
      TS_real_Infectious[i,j+k]=TS_real_Infectious[i,j+k]-k*TS_real_Infectious[i,j]
    }
  }
}
```
```{r}
library(plyr)
TS_real_rate<-join(TS_real_Infectious,Trip_goout_rate[1:51,-(2:3)],by="X1")
for(i in 3:ncol(TS_real_Infectious)){
  TS_real_rate[,i]<-TS_real_rate[,i]/as.numeric(TS_real_rate$X4)
}
TS_real_rate

```
```{r}
Beta_i_t<-TS_real_Infectious
ratio<-10000000
for(j in 1:50){
  state_in_j<-get(paste0("states_in",j))
  state_out_j<-get(paste0("states_out",j))
  state_in_j<-state_in_j[which(state_in_j$time=="2020/04/01"):nrow(state_in_j),]
  state_out_j<-state_out_j[which(state_out_j$time=="2020/04/01"):nrow(state_out_j),]
  for(i in 3:(ncol(Beta_i_t)-1)){
    Beta_i_t[j,i]<-TS_real_Infectious[j,i+1]-TS_real_Infectious[j,i]*(1-gamma)
    for(k in 1:50){
      if(k!=j){
        Beta_i_t[j,i]=Beta_i_t[j,i]-state_in_j[i-2,k]*TS_real_rate[k,i]
      }
    }
    Beta_i_t[j,i]=Beta_i_t[j,i]+TS_real_rate[j,i]*rowSums(state_out_j[,-51])[i-2]
    Beta_i_t[j,i]=ratio*Beta_i_t[j,i]/TS_real_Infectious[j,i]/(as.numeric(TS_real_rate$X4[j])-TS_covid_state_select[j,i])
  }
}
Beta_i_t<-Beta_i_t[,1:which(colnames(Beta_i_t)=="2021/04/01")]
```
```{r}
write.csv(Beta_i,file="E:/wzy/wzy/bigchuangdata/Beta.csv")
write.csv(Beta_i_t,file="E:/wzy/wzy/bigchuangdata/Beta_t.csv")

```

```{r}
k<-0
for(i in 1:50){
  temp<-as.matrix(Beta_i_t[i,3:ncol(Beta_i_t)])
  box<-boxplot.stats(temp,coef=3)
  for(j in 3:ncol(Beta_i_t)){
    if(is.na(Beta_i_t[i,j])==1){
      next
    }
    if(Beta_i_t[i,j]>box$stats[5]|Beta_i_t[i,j]<box$stats[1]){
      Beta_i_t[i,j]=NA
      k=k+1
    }
  }
}
beta_mean<-rowMeans(Beta_i_t[,3:ncol(Beta_i_t)],na.rm=TRUE)
sd_beta<-rep(0,50)
for(i in 1:50){
  sd_beta[i]<-sd(Beta_i_t[i,3:ncol(Beta_i_t)],na.rm=TRUE)  
}
beta_mean<-data.frame(Beta_i_t$X1,beta_mean)
write.csv(beta_mean,file="E:/wzy/wzy/bigchuangdata/Beta_mean.csv")
beta_mean
```
```{r}
mean_delta_beta<-rep(0,50)
sd_delta_beta<-rep(0,50)
for(j in 1:50){
  temp<-matrix(Beta_i_t[j,3:ncol(Beta_i_t)])
  mat<-rep(0,nrow(temp)-1)
  for(i in 2:nrow(temp)){
    mat[i-1]=as.numeric(temp[i,1])-as.numeric(temp[i-1,1])
  }
  mean_delta_beta[j]<-mean(mat,na.rm=TRUE)
  sd_delta_beta[j]<-sd(mat,na.rm = TRUE)
}
sd_delta_beta
```
```{r}
write.csv(mean_delta_beta,file="E:/wzy/wzy/bigchuangdata/Mean_delta_beta.csv")
```


```{r}
Beta_sd<-rep(0,50)
for(i in 1:50){
  Beta_sd[i]<-sd(Beta_i_t[i,3:ncol(Beta_i_t)],na.rm = TRUE)
}
plot(matrix(Beta_i_t[16,3:ncol(Beta_i_t)]))
```
```{r}
beta_simulate<-matrix(0,nrow=50,ncol=150)
for(j in 1:50){
  beta_start=Beta_i_t[j,which(colnames(TS_real_Infectious)=="2021/01/01")]
  delta_beta_simulate<-rnorm(150,mean=mean_delta_beta[j],sd=sd_delta_beta[j])
  beta_simulate[j,1]=beta_start
  state_num<-as.numeric(TS_real_rate$X4[j])
  for(i in 2:150){
    beta_simulate[j,i]=beta_simulate[j,i-1]+delta_beta_simulate[i]
    if(is.na(beta_simulate[j,i])|beta_simulate[j,i]<0){
      beta_simulate[j,i]=0
    }
  }
}
```
```{r}
setwd("E:/wzy/wzy/bigchuangdata")
Vaccine_data<-read.csv(file="vaccine_data_us_timeline.csv")
Vaccine_data<-Vaccine_data[which(Vaccine_data$Vaccine_Type=="All"),c(1,2,10)]
Vaccine_data
```

```{r}
gamma<-1/3
n<-which(colnames(TS_real_Infectious)=="2021/01/01")
infect_num<-matrix(0,nrow=50,ncol=150)
for(j in 1:50){
  infect_num[j,1]<-TS_real_Infectious[j,which(colnames(TS_real_Infectious)=="2021/01/01")]
}
state_num<-as.numeric(TS_real_rate$X4)
Recovered<-TS_covid_state_select[,which(colnames(TS_covid_state_select)=="X1.1.21")]+TS_real_Infectious[,n]
for(i in 2:150){
  for(j in 1:50){
    Vaccine_data_state<-Vaccine_data[Vaccine_data$Province_State==TS_real_Infectious$Group.1[j],]
    Vaccine_data_state=Vaccine_data_state[which(Vaccine_data_state$Date=="2021-01-01"):nrow(Vaccine_data_state),]
    state_out_j<-get(paste0("states_out",j))
    infect_num[j,i]<-infect_num[j,i-1]*(1-gamma)+max(c(rnorm(1,mean=beta_mean$beta_mean[j],sd=sd_beta[j]),0))*infect_num[j,i-1]*(state_num[j]-infect_num[j,i-1]-Recovered[j]-ifelse(is.na(Vaccine_data_state[i,3]),0,Vaccine_data_state[i,3]))/ratio
    for(k in 1:50){
      if(k!=j){
        state_in_k<-get(paste0("states_in",k))
        infect_num[j,i]=infect_num[j,i]+state_in_k[nrow(state_in_k),j]*infect_num[k,i-1]/(state_num[j])
      }
    }
    infect_num[j,i]=infect_num[j,i]-infect_num[j,i-1]/(state_num[j])*rowSums(state_out_j[,1:50])[which(state_out_j$time=="2021/01/01")]
    if(infect_num[j,i]>state_num[j]){
      infect_num[j,i]=state_num[j]
    }
    Recovered[j]=Recovered[j]+infect_num[j,i]
  }
}

```
```{r}
for(j in 1:50){
  jpeg(file=paste0("E:/wzy/wzy/bigchuangdata/pre_pictures/predict_",TS_new_cases[j,1],".jpg"),width = 1000, height = 700)
  data_old<-matrix(TS_new_cases[j,which(colnames(TS_new_cases)=="2020/04/01"):which(colnames(TS_new_cases)=="2021/01/01")])
  data_merge<-rbind(data_old,matrix(infect_num[j,])*gamma)
  plot(data_merge,ylab="new cases",xlab="date from 2020/04/01",main=paste0("Predict from 2021/01/01 in ",TS_new_cases[j,1]),type="l", col="red")
  abline(v=n,col="blue",lty=2)
  lines(matrix(TS_new_cases[j,3:ncol(TS_new_cases)]),col="black")
  legend("topright", legend=c("pre","real"), col=c("red", "black"),  lty=1)
  dev.off()
}
```

```{r}
j<-5
Recovered/state_num
```

```{r}
get(paste0("states_in",5))
```

```{r}

```

